# Generated by Django 5.2.8 on 2025-11-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository_url",
                    models.URLField(blank=True, max_length=2550, null=True),
                ),
                (
                    "scan_depth",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("DEEP", "Deep")],
                        max_length=20,
                    ),
                ),
                ("include_history", models.BooleanField(default=False)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("SECRETS", "Secrets"),
                            ("DEPENDENCIES", "Dependencies"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
                ("file_path", models.CharField(max_length=2550)),
                ("str_number", models.PositiveIntegerField()),
                (
                    "bug_type",
                    models.CharField(
                        choices=[
                            ("SECRETS", "Secrets"),
                            ("DEPENDENCIES", "Dependencies"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scan_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_results",
                        to="scanner.scanrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
