# Generated by Django 5.2.8 on 2025-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrequest",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanrequest",
            name="local_path",
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name="scanrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("DOWNLOADING", "Скачивание репозитория"),
                    ("SCANNING", "Сканирование"),
                    ("COMPLETED", "Завершено"),
                    ("FAILED", "Ошибка"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="raw_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="secret_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="str_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
